<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Imovel extends Model
{
    use HasFactory;

    protected $table = 'imoveis'; 
    
    protected $fillable = [
        'venda',
        'locacao',
        'categoria',
        'tipo',
        'proprietario',
        'exibivalores',
        'valor_venda',
        'valor_locacao',
        'iptu',
        'ano_construcao',
        'referencia',
        'condominio',
        'descricao',
        'notasadicionais',
        'dormitorios',
        'suites',
        'banheiros',
        'salas',
        'garagem',
        'garagem_coberta',
        'anodeconstrucao',
        'area_total',
        'area_util',
        'medidas',
        'latitude',
        'longitude',
        'exibirendereco',
        'cep',
        'rua',
        'num',
        'complemento',
        'bairro',
        'uf',
        'cidade',
        'ar_condicionado',
        'aquecedor_solar',
        'bar',
        'biblioteca',
        'churrasqueira',
        'estacionamento',
        'cozinha_americana',
        'cozinha_planejada',
        'dispensa',
        'edicula',
        'espaco_fitness',
        'escritorio',
        'fornodepizza',
        'armarionautico',
        'portaria24hs',
        'quintal',
        'zeladoria',
        'salaodejogos',
        'saladetv',
        'areadelazer',
        'balcaoamericano',
        'varandagourmet',
        'banheirosocial',
        'brinquedoteca',
        'pertodeescolas',
        'condominiofechado',
        'interfone',
        'sistemadealarme',
        'jardim',
        'salaodefestas',
        'permiteanimais',
        'quadrapoliesportiva',
        'geradoreletrico',
        'banheira',
        'lareira',
        'lavabo',
        'lavanderia',
        'elevador',
        'mobiliado',
        'vista_para_mar',
        'piscina',
        'sauna',
        'ventilador_teto',
        'titulo',
        'slug',
        'status',
        'views',        
        'metatags',
        'headline',
        'exibirmarcadagua',
        'legendaimgcapa',
        'mapadogoogle',
        'experience',
        'destaque',
        'publication_type'
    ];
}
